[app]
name = "demo"
host = "0.0.0.0"
port = "8088"
key  = "this is your app key"

[mysql]
host = "192.168.3.102"
port = "3306"
username = "root"
password = "123456"
database = "calf-go"

[log]
# // DebugLevel: "debug",
# // InfoLevel:  "info",
# // WarnLevel:  "warning",
# // ErrorLevel: "error",
# // FatalLevel: "fatal",
# // PanicLevel: "panic",
level = "debug"
format = "text"
to = "stdout"